---
# debug vars
- name: Debug | Print Karbon cluster definition
  debug:
    msg: |
      karbon_cluster_name = {{ karbon_cluster_name }}
      cluster_name = {{ cluster_name }}
      cluster_uuid = {{ cluster_uuid }}
      cluster_username = {{ cluster_username }}
      cluster_password = {{ cluster_password }}
      subnet_name = {{ subnet_name }}
      subnet_uuid = {{ subnet_uuid }}
      container_name = {{ container_name }}
      cluster_type = {{ cluster_type }}
      kubernetes_version = {{ kubernetes_version }}
      service_ipv4_cidr = {{ service_ipv4_cidr }}
      pod_ipv4_cidr = {{ pod_ipv4_cidr }}
      node_cidr_mask_size = {{ node_cidr_mask_size }}
      flash_mode = {{ flash_mode }}
      karbon_image_version = {{ karbon_image_version }}
      master = {{ master_count }} x [ {{ master_vcpu }} CPU, {{ master_memory_mib }} MB RAM, {{ master_disk_mib }} MB DISK ]
      etcd = {{ etcd_count }} x [ {{ etcd_vcpu }} CPU, {{ etcd_memory_mib }} MB RAM, {{ etcd_disk_mib }} MB DISK ]
      worker = {{ worker_count }} x [ {{ worker_vcpu }} CPU, {{ worker_memory_mib }} MB RAM, {{ worker_disk_mib }} MB DISK ]
  when: global_debug


# debug template
- name: Debug | Print Template lookup result
  debug:
    msg: "{{ lookup('template', 'karbon-body.yml.j2') | from_yaml }}"
  when: global_debug


# post template to api
- name: Create a Karbon cluster from template
  uri:
    url: "{{ prism_central_karbon_api }}/v1/k8s/clusters"
    body: "{{ lookup('template', 'karbon-body.yml.j2') | from_yaml }}"
    method: POST
    validate_certs: "{{ validate_certs }}"
    body_format: json
    headers:
      Cookie: "{{ session_cookie }}"
    status_code: 202
  register: json_create_result


# debug template
- name: Debug | Print Karbon cluster creation result
  debug:
    msg: "{{ json_create_result }}"
  when: global_debug


# wait for task to complete
- name: "Wait until {{ karbon_cluster_name }} deployment complete"
  uri:
    url: "{{ prism_central_karbon_api }}/v1-alpha.1/k8s/clusters/{{ karbon_cluster_name }}/tasks/{{ json_create_result.json.task_uuid }}"
    method: GET
    validate_certs: "{{ validate_certs }}"
    status_code: 200
  register: karbon_create_status
  until:
  - karbon_create_status.status == 200
  - ( karbon_create_status.json.percentage_complete == 100 and karbon_create_status.json.status == "kSucceeded" )
  - ( karbon_create_status.json.status == "kFailed" )
  retries: 60
  delay: 30
  when: wait


# debug template
- name: Debug | Print Karbon cluster creation task result
  debug:
    msg: "{{ karbon_create_status.json.status }}"
  when: global_debug


# get provisioned karbon cluster details
- name: Get Karbon cluster info
  uri:
    url: "{{ prism_central_karbon_api }}/v1/k8s/clusters/{{ karbon_cluster_name }}"
    method: GET
    validate_certs: "{{ validate_certs }}"
    headers:
      Cookie: "{{ session_cookie }}"
    status_code: 200
  register: karbon_cluster_info
  when: >
    ( wait ) and
    ( karbon_create_status.json.status == "kSucceeded" )


# debug template
- name: Debug | Print Karbon cluster info
  debug:
    msg: "{{ karbon_cluster_info }}"
  when: >
    ( wait ) and
    ( karbon_create_status.json.status == "kSucceeded" ) and
    global_debug


# get provisioned karbon cluster kubeconfig
- name: Get provisioned Karbon cluster kubeconfig
  uri:
    url: "{{ prism_central_karbon_api }}/v1/k8s/clusters/{{ karbon_cluster_name }}/kubeconfig"
    method: GET
    validate_certs: "{{ validate_certs }}"
    headers:
      Cookie: "{{ session_cookie }}"
    status_code: 200
  register: karbon_cluster_kubeconfig
  when: >
    ( wait ) and
    ( karbon_create_status.json.status == "kSucceeded" )


# debug template
- name: Debug | Print Karbon cluster kubeconfig
  debug:
    msg: "{{ karbon_cluster_kubeconfig }}"
  when:  >
    ( wait ) and
    ( karbon_create_status.json.status == "kSucceeded" ) and
    global_debug
